spring:
  application:
    name: microservice-shop

server:
  port: 8080

api:
  storage:
    uriGetProducts: http://localhost:8081/warehouse/getProducts
    uriGetProduct: http://localhost:8081/warehouse/getProduct/
    reserveProduct: http://localhost:8081/warehouse/reserveProduct



management:
  endpoints:
    web:
      exposure:
        include: env, info, health, metrics,prometheus
        #include=*
    health:
      show-details: always

